import type { Metadata } from "next";
import "./globals.css";
import Providers from "../components/Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import SessionProvider from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <main>
          <SessionProvider session={session}>
            <Providers>
              <div>{children}</div>
            </Providers>
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
